export { About } from './about/about'
export { Catalog } from './catalog/catalog'
export { Contacts } from './contacts'
export { Delivery } from './delivery/delivery'
export { Footer } from './footer/footer'
export { Header } from './header/header'
export { MobileMenu } from './mobile-menu/mobile-menu'
export { Navbar } from './navbar/navbar'
export { Promo } from './promo/promo'
export { SearchBar } from './search-bar/search-bar'
export * from './news'
export * from './modal'
export * from './products'
