export { About } from './about/about'
export { Advantages } from './advantages/advantages'
export { Catalog } from './catalog/catalog'
export { Contacts } from './contacts'
export { Delivery } from './delivery/delivery'
export { Footer } from './footer/footer'
export { Header } from './header/header'
export { MobileMenu } from './mobile-menu/mobile-menu'
export { Navbar } from './navbar/navbar'
export { Promo } from './promo/promo'
export { PromoOther } from './promo-other/promo-other'
export { SearchBar } from './search-bar/search-bar'
export { Quality } from './quality/quality'
export { VideoPlayer } from './video-player/video-player'
export * from './news'
export * from './modal'
export * from './products'
